name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: set git config
      run: |
        sudo git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/smilep/safety-checker.git
        sudo git config --local user.email "action@github.com"
        sudo git config --local user.name "GitHub Action"
    
    - name: install
      run: |
        sudo npm install

    - name: deploy to GitHub pages
      run: |
        sudo npm run deploy
